MoodleIt/Models/Announcement.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoodleIt.Models
{
    public class Announcement
    {
        [Display(Name = "Announcment ID")]
        public int AnnouncementId { get; set; }
        public int CourseId { get; set; }

        [DataType(DataType.MultilineText)]
        [Display(Name = "Announcement")]
        [MaxLength(500)]
        public string AnnouncementDescription { get; set; }
        [Display(Name = "Title")]
        [MaxLength(30)]
        public string AnnouncementTitle { get; set; }

        [Display(Name = "Date")]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime Date { get; set; }

        public virtual Course Course { get; set; }

    }
}

MoodleIt/Models/Student.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoodleIt.Models
{
    public class Student
    {
        [Display(Name = "Student ID")]
        public int StudentId { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
        public string StudentUserNumber { get; set; }

        public virtual ICollection<Enrollment> Enrollments { get; set; }
        public virtual ICollection<Homework> Homeworks { get; set; }
    }
}

MoodleIt/ViewModels/ContactList.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using MoodleIt.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MoodleIt.ViewModels
{
    public class ContactList
    {
        [Display(Name = "Student ID")]
        public int StudentId { get; set; }
        public int EnrollmentId { get; set; }
        public int CourseId { get; set; }
        [Display(Name = "Course Name")]
        public Courses CourseName { get; set; }
        [Display(Name = "Course Number")]
        public int CourseNumber { get; set; }
        [Display(Name = "Full Name")]
        public string FullName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }
}

MoodleIt/Controllers/StudentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Data;
using System.Data.Entity;
using System.Net;
using PagedList;
using Newtonsoft.Json;


using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security;
using MoodleIt.Logic;
using MoodleIt.Models;
using MoodleIt.ViewModels;

using System.IO;


namespace MoodleIt.Controllers
{
    [Authorize(Roles = "Student")] //Only a student user can access this controller
    public class StudentsController : Controller
    {
        UniversityDbContext db = new UniversityDbContext();
        StudentCourseActions sca = new StudentCourseActions();

        //
        // GET: /Students/MyProfile
        public ActionResult MyProfile(string currentUserId)
        {
            string currentUser = User.Identity.GetUserId(); //User ID of the current logged-in student
            int studId = sca.GetStudentId(currentUser); //Find the student Id by the current user id
            var stud = sca.GetStudentById(studId);

            return View(stud);
        }

        //***FUTURE OPTION FOR REGISTRATION TO MORE THAN ONE COURSE***:

        // GET: /Students/RegisterToCourse
        public ActionResult RegisterToCourse()
        {
            ViewBag.CourseNames = new SelectList(sca.GetCourseName(), "CourseName", "CourseName".ToString());

            return View();
        }

        // POST: /Students/RegisterToCourse
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterToCourse([Bind(Include = "CourseName,CourseStartDate")] 
            Course course)
        {
            if (ModelState.IsValid)
            {
                int courseId = sca.GetCourseId(course.CourseName, course.CourseStartDate);
                string currentUser = User.Identity.GetUserId();
                int studentId = sca.GetStudentId(currentUser);
                sca.AddEnrollment(studentId, courseId);

                return RedirectToAction("MyProfile");
            }

            return View(course);
        }

        [HttpPost]
        public ActionResult GetCourseStartDate(string courseName) 
        {
            Courses x;
            switch (courseName)
            {
                case "AngularJS":
                    Enum.TryParse("AngularJS", out x);
                    break;
                case "CSS":
                    Enum.TryParse("CSS", out x);
                    break;
                default:
                    Enum.TryParse("HTML", out x);
                    break;
            }
            List<Course> dates = sca.GetCourseDate(x);
            var list = dates.Select(d => d.CourseStartDate).ToList();

            ViewBag.DateOptions = new SelectList(list, "CourseStartDate", "CourseStartDate");

            string result = JsonConvert.SerializeObject(list);

            return Json(result, JsonRequestBehavior.AllowGet);
        }

        //
        // GET: /Students/MyAssignmetns
        public ActionResult MyAssignmetns(string sortOrder, string searchText,
            string currentFilter, int? page)
        {
            string currentUser = User.Identity.GetUserId(); //User ID of the current logged-in student
            int studId = sca.GetStudentId(currentUser);           

            ViewBag.CurrentSort = sortOrder;

            //Ternary Operator- short way of "if"
            ViewBag.AssignmentIdSort =
                sortOrder == "AssignmentIdAsc" ? "AssignmentIdDesc" : "AssignmentIdAsc";
            ViewBag.CourseNumberSort =
                sortOrder == "CourseNumberAsc" ? "CourseNumberDesc" : "CourseNumberAsc";
            ViewBag.CourseNameSort =
                sortOrder == "CourseNameAsc" ? "CourseNameDesc" : "CourseNameAsc";
            ViewBag.StartDateSort =
                sortOrder == "StartDateAsc" ? "StartDateDesc" : "StartDateAsc";
            ViewBag.AssignmentTitleSort =
                sortOrder == "AssignmentTitleAsc" ? "AssignmentTitleDesc" : "AssignmentTitleAsc";
            ViewBag.DeadLineSort =
                sortOrder == "DeadLineAsc" ? "DeadLineDesc" : "DeadLineAsc";

            if (searchText != null)
            {
                page = 1;
            }
            else
            {
                searchText = currentFilter;
            }
            ViewBag.CurrentFilter = searchText; //Saves the filter and sorting while paging

            var assignments = sca.ShowStudentAssignments(studId);

            if (!string.IsNullOrEmpty(searchText))
            {
                assignments = assignments.Where(s =>
                    s.CourseNumber.ToString().Contains(searchText) ||
                    s.CourseName.ToString().Contains(searchText) ||
                    s.StartDate.ToString().Contains(searchText) ||
                    s.AssignmentTitle.ToString().Contains(searchText) ||
                    s.DeadLine.ToString().Contains(searchText)).ToList();
            }

            switch (sortOrder)
            {
                case "CourseNumberAsc":
                    assignments = assignments.OrderBy(s => s.CourseNumber);
                    break;
                case "CourseNumberDesc":
                    assignments = assignments.OrderByDescending(s => s.CourseNumber);
                    break;
                case "CourseNameAsc":
                    assignments = assignments.OrderBy(s => s.CourseName);
                    break;
                case "CourseNameDesc":
                    assignments = assignments.OrderByDescending(s => s.CourseName);
                    break;
                case "StartDateAsc":
                    assignments = assignments.OrderBy(s => s.StartDate);
                    break;
                case "StartDateDesc":
                    assignments = assignments.OrderByDescending(s => s.StartDate);
                    break;
                case "AssignmentTitleAsc":
                    assignments = assignments.OrderBy(s => s.AssignmentTitle);
                    break;
                case "AssignmentTitleDesc":
                    assignments = assignments.OrderByDescending(s => s.AssignmentTitle);
                    break;
                case "DeadLineAsc":
                    assignments = assignments.OrderBy(s => s.DeadLine);
                    break;
                case "DeadLineDesc":
                    assignments = assignments.OrderByDescending(s => s.DeadLine);
                    break;
                default:
                    assignments = assignments.OrderBy(s => s.AssignmentId);
                    break;
            }

            int pageSize = 5;
            int pageNumber = page ?? 1;
            return View(assignments.ToPagedList(pageNumber, pageSize));
        }

        // GET: /Students/AssignmentDetails
        public ActionResult AssignmentDetails(int? id)
        {
            var assignment = sca.GetAssignmentById(id);
            return View(assignment);
        }

        //
        // GET: /Students/MyHomework
        public ActionResult MyHomework(string currentUserId)
        {

            string currentUser = User.Identity.GetUserId(); //User ID of the current logged-in student
            int studId = sca.GetStudentId(currentUser);

            var hw = sca.ShowStudentHomework(studId);

            return View(hw);
        }

        // This action handles the form POST and the upload
        [HttpPost]
        public ActionResult MyHomeworkStatus(HttpPostedFileBase file, int assignmentID)
        {
            ViewBag.UploadFailed = "";

            //Gets only the extension of the file (.doc for example).
            string fileExtension = Path.GetExtension(file.FileName).ToLower();

            //The uploaded file will be saved with a name that is consisted of the properties below:
            string courseName = sca.GetCourseNameByAssignmentId(assignmentID);
            string startDate = sca.GetCourseStartDateByAssignmentId(assignmentID);
            string currentUser = User.Identity.GetUserId();
            int studentId = sca.GetStudentId(currentUser);
            string studentName = sca.GetUserFullNameByIdWithoutSpace(studentId);
            string sendDate = DateTime.Today.ToString("ddMMyyyy");
            string assignment = "Assignment_" + assignmentID + "_";

            string folder = courseName + "_" + startDate; //The file will be saved to this folder
            string fileName = folder + "_" + studentName + "_" + assignment + sendDate;

            var newfolder = Server.MapPath("~/UploadedFiles/" + folder); //New folder to create
            if (!Directory.Exists(newfolder)) //If the folder does not exist, then create it:
            {
                Directory.CreateDirectory(newfolder);
            }

            string path = Server.MapPath("~/UploadedFiles/" + folder + "/"); //The path in which the file is saved 

            int selectedFilesCount = Request.Files.Count; //Allow the upload only when ONE file is selected

            switch (selectedFilesCount)
            {
                case 1:
                    string[] allowExtensions = { ".doc", ".docx", ".pdf", ".rtf" }; //Only these extensions are allowed
                    string fileNameWithExtension = fileName + fileExtension;
                    if (allowExtensions.Contains(fileExtension))
                    {
                        try
                        {
                            //Save the file to the server
                            file.SaveAs(path + fileName + fileExtension);
                            if (sca.HomeworkExists(studentId, assignmentID)) 
                            {
                                //This method is used to update the desired homework instead of duplicate the file

MoodleIt/Views/Students/AnnouncementDetails.cshtml
@model IEnumerable<MoodleIt.ViewModels.ShowAnnouncements>

@{
    ViewBag.Title = "Announcement Details";
}
<h2>Announcement Details</h2>
<img src="~/Catalog/announcement.png" height="100" />
<hr />
<div>
    <h4>@Html.DisplayFor(model => model.FirstOrDefault().AnnouncementTitle)</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt style="text-align: left; width: auto; margin-right: 4px;">
            @Html.DisplayNameFor(model => model.AnnouncementId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstOrDefault().AnnouncementId)
        </dd>

        <dt style="text-align: left; width: auto; margin-right: 4px;">
            @Html.DisplayNameFor(model => model.Date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstOrDefault().Date)
        </dd>
        <dt style="text-align: left; width: auto; margin-right: 4px;">
            @Html.DisplayNameFor(model => model.AnnouncementDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstOrDefault().AnnouncementDescription)
        </dd>



    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Announcements")
</p>

MoodleIt/Views/Students/Announcements.cshtml
@model IEnumerable<MoodleIt.Models.Announcement>

@{
    ViewBag.Title = "Announcements";
}
<h2>Announcements from the teacher</h2>
<img src="~/Catalog/announcement.png" height="100"/>
<hr />
@using (Html.BeginForm("Announcements", "Students", FormMethod.Get))
{
    <p>
        Search by course name: @Html.DropDownList("ddlSelectedName", (SelectList)ViewBag.coursesList,
    "Select a Course", new { @class = "form-control" })
    </p>
    <p>
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AnnouncementId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AnnouncementTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Date)
        </th>

    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AnnouncementId)
            </td>
            <td>
                @Html.ActionLink(item.AnnouncementTitle, "AnnouncementDetails", new { id = item.AnnouncementId })
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
        </tr>
    }
</table>

MoodleIt/Views/Students/AssignmentDetails.cshtml
@model IEnumerable<MoodleIt.Models.Assignment>

@{
    ViewBag.Title = "Assigment Details";
}
<h2>Assignment #@Html.DisplayFor(model => model.FirstOrDefault().AssignmentId) Details</h2>

<div>
    <h4>@Html.DisplayFor(model => model.FirstOrDefault().AssignmentTitle)</h4>
    <hr />
    <dl>
        <dt style="text-align:left">
            @Html.DisplayNameFor(model => model.DeadLine)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstOrDefault().DeadLine)
        </dd>

        <dt style="text-align:left">
            @Html.DisplayNameFor(model => model.AssignmentDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstOrDefault().AssignmentDescription)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "MyAssignmetns")
</p>

MoodleIt/Views/Students/ContactList.cshtml
@model PagedList.IPagedList<MoodleIt.ViewModels.ContactList>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Contact List";
}
<h2>Students who study with me</h2>
<img src="~/Catalog/contactlist.png" height="100"/>
<hr />

@using (Html.BeginForm("ContactList", "Students", FormMethod.Get))
{
    <p>
        Find student by Full Name / Email / Phone Number:
    </p>
    <p>
        @Html.TextBox("SearchText", ViewBag.CurrentFilter as string, new { @class = "form-control" })
    </p>
    <p>
        <input type="submit" value="Search" class="btn btn-default" />
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Student ID", "ContactList",
            new
            {
                sortOrder = ViewBag.StudentIdSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Full Name", "ContactList",
            new
            {
                sortOrder = ViewBag.FullNameSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Email", "ContactList",
            new
            {
                sortOrder = ViewBag.EmailSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Phone Number", "ContactList",
            new
            {
                sortOrder = ViewBag.PhoneNumberSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Course Name", "ContactList",
            new
            {
                sortOrder = ViewBag.CourseNameSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Course Number", "ContactList",
            new
            {
                sortOrder = ViewBag.CourseNumberSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.StudentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PhoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseNumber)
            </td>
        </tr>
    }
</table>

<br /><br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
@Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("ContactList",
            new
            {
                page,
                sortOrder = ViewBag.CurrentSort,
                currentFilter = ViewBag.CurrentFilter
            }))

MoodleIt/Views/Students/MyAssignmetns.cshtml
@model PagedList.IPagedList<MoodleIt.ViewModels.ShowAssignments>
@using PagedList.Mvc;

@* In this page, there's a list of all the assignment that are relevant for the current student *@

@{
    ViewBag.Title = "My Assigments";
}
<h2>My Assignments</h2>
<img src="~/Catalog/assignment.png" height="100"/><br /><br />
<hr />
@Html.ActionLink("Upload Homework and Check for Grades", "MyHomework")

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Assignment ID", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.AssignmentIdSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Course Number", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.CourseNumberSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Course Name", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.CourseNameSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Start Date", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.StartDateSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Assignment Title", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.AssignmentTitleSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Dead Line", "MyAssignmetns",
            new
            {
                sortOrder = ViewBag.DeadLineSort,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssignmentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CourseName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StartDate)
            </td>
            <td>
                @Html.ActionLink(item.AssignmentTitle, "AssignmentDetails", new { id = item.AssignmentId })
            </td>

            <td>
               @if((item.DeadLine - DateTime.Today).TotalDays < 7 &&
                   (item.DeadLine - DateTime.Today).TotalDays > 0)
               {
                  @Html.DisplayFor(modelItem => item.DeadLine)
                   <span style="color:red">&nbsp;@((item.DeadLine - DateTime.Today).TotalDays) days left!</span>
               }
               @if(DateTime.Compare(DateTime.Today, item.DeadLine) > 0)
               {
                   <s>@Html.DisplayFor(modelItem => item.DeadLine)</s>
               }
               @if ((item.DeadLine - DateTime.Today).TotalDays >= 7)
               {                   
                @Html.DisplayFor(modelItem => item.DeadLine)
               }
            </td>
        </tr>
    }

</table>
<br /><br />

Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of
@Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("MyAssignmetns",
            new
            {
                page,
                sortOrder = ViewBag.CurrentSort,
                currentFilter = ViewBag.CurrentFilter
            }))

MoodleIt/Views/Students/MyHomework.cshtml
@model IEnumerable<MoodleIt.ViewModels.ShowHomework>

@* In this page, the student can upload homework. The grades are shown in this page. *@

@{
    ViewBag.Title = "My Homework";
}
<h2>My Homework</h2>
<img src="~/Catalog/uploadFile.png" height="100"/>
<hr />

<div class="alert alert-dismissible alert-warning">
    <p>Only .doc, .docx, .pdf, .rtf are allowed!</p>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AssignmentId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DeadLine)
        </th>
        <th>
            Upload Homework
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeworkSent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SendDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.HomeworkChecked)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Grade)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AssignmentId)
            </td>
            <td>
                @if (DateTime.Compare(DateTime.Today, item.DeadLine) <= 0)
                {
                    @Html.DisplayFor(modelItem => item.DeadLine)
                }
                else
                {
                    <font color="red">
                        @Html.DisplayFor(modelItem => item.DeadLine)
                    </font>
                }
            </td>
            <td>
                @using (Html.BeginForm("MyHomeworkStatus", "Students", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    if (DateTime.Compare(DateTime.Today, item.DeadLine) <= 0)
                    {
                        <input type="file" name="file" />
                        <input type="hidden" name="assignmentID" value="@Html.DisplayFor(modelItem => item.AssignmentId)" />
                        <input type="submit" value="Send File" />
                    }
                    else
                    {
                        <input type="submit" value="Send File" disabled />
                    }
                }
            </td>
            <td>
                @if (item.HomeworkSent == false)
                {
                    <p>Not Yet</p>
                }
                else
                {
                    <p>Yes</p>
                }

            </td>
            <td>
                @if (item.SendDate == null)
                {
                    <p>N/A</p>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.SendDate)
                }
            </td>
            <td>
                @if (item.HomeworkChecked == false)
                {
                    <p>Not Yet</p>
                }
                else
                {
                    <p>Yes</p>
                }
            </td>
            <td>
                @if (item.CheckDate == null)
                {
                    <p>N/A</p>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.CheckDate)
                }
            </td>
            <td>
                @if (DateTime.Compare(DateTime.Today, item.DeadLine) < 0 && item.HomeworkChecked == false
                  && item.Grade == 0)
                {
                    <p>N/A</p>
                }
                @if (DateTime.Compare(DateTime.Today, item.DeadLine) > 0 && item.HomeworkSent == false)
                {
                    <p>N/A</p>
                }
                else
                {
                    <b>@Html.DisplayFor(modelItem => item.Grade)</b>
                }
            </td>
        </tr>
    }

</table>

@Html.ActionLink("Back to My Assignments", "MyAssignmetns", "Students")<br />

MoodleIt/Views/Students/MyProfile.cshtml
@model MoodleIt.Models.Student

@{
    ViewBag.Title = "My Profile";
}
<h2>My Profile</h2>
<h4>@Html.DisplayFor(model => model.FullName)</h4>
<img src="~/Catalog/myProfile.png" height="100"/>
<hr />
<dl class="dl-horizontal">
    <dt style="text-align:left">
        @Html.DisplayNameFor(model => model.StudentId)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.StudentId)
    </dd>

    <dt style="text-align:left">
        @Html.DisplayNameFor(model => model.FullName)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.FullName)
    </dd>

    <dt style="text-align:left">
        @Html.DisplayNameFor(model => model.Email)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.Email)
    </dd>
    <dt style="text-align:left">
        @Html.DisplayNameFor(model => model.PhoneNumber)
    </dt>

    <dd>
        @Html.DisplayFor(model => model.PhoneNumber)
    </dd>
</dl>